### ISSUE TITLE
example in blog doesn't work

### ISSUE THREAD

**Issue by HowJMay** [iden3/circom#20] opened 2021-11-04 16:18 UTC
The tutorial here doesn't work on Apple M1.

https://blog.iden3.io/first-zk-proof.html

So does the visual summary in home page of official document here
https://docs.circom.io/

**Comment by a2468834** [comment] 2021-11-23 14:37
If you want some tutorial of codes, I suggest [this page](https://docs.circom.io/getting-started/writing-circuits/). Because there are some changes in syntax between version "<=1" and ">=2", you could face compile errors when you follow the old page but use Circom 2.0.

**Comment by alrubio** [comment] 2021-12-13 08:12
If you work with the WebAssembly backend (using --wasm) it should work (following the instructions in https://docs.circom.io/) for M1 as well. It does not work if you use --c, but I don't know whether this is the problem you've found.

**Comment by alrubio** [comment] 2021-12-13 08:15
If you were following https://blog.iden3.io/first-zk-proof.html, then, as mentioned, the problem is the circom version.
If this was the case, I'll proceed to close the issue.

**Closed** 2021-12-21 11:52 UTC
